### ISSUE TITLE
Remove IDISP014 / disable by default?

### ISSUE THREAD

**Issue by Bouke** [DotNetAnalyzers/IDisposableAnalyzers#216]
While IDISP014 can be valuable, I don't see a reason why it should be part of this analyzer. Managing the lifetime of an HttpClient is dependent on the specific use-case and "just use a single static instance" just doesn't hold true for all use-cases. Some might want to set default headers for a some instance, but not for all outgoing requests. Some other instances might receive credentials, but those shouldn't leak to other instances as well.

Situations where sharing an instance makes sense:
- When doing a lot of homogenous requests

Situations where sharing an instance doesn't make sense:
- When default request arguments are provided that shouldn't be shared

Situations where sharing an instance doesn't matter:
- When doing only a few requests

**Comment by JohanLarsson** [comment]
Valid point, default disabled perhaps better.
One downside with default disabled is discoverability close to zero.

**Comment by jeremyVignelles** [comment]
FWIW: I've disabled that rule on uses cases like unit testing,

In ASP.net core 2.something, this rule is easy to apply because of the new IHttpClientFactory, which manages the HttpClient lifetimes for you, but when you don't have access to a IHttpClientFactory, you might want to use different handlers for different usages (not the same certificate validation policy...)

Maybe we could make it an info rather than a warning?

**Comment by JohanLarsson** [comment]
Changing it to default info is perhaps a nice compromise, what do you think about that @Bouke?

**Comment by Bouke** [comment]
I think that’s a good trade-off!
